# Generated by Django 3.2.18 on 2023-02-28 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230228_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
